### ISSUE TITLE
Make blacklist configurable

### ISSUE THREAD

**Issue by akoehn** [minecraft-saar/spigot-plugin#21]
I would love to have an easy way of disabling user banning without the need to recompile the spigot plugin.  Maybe that is already possible but not documented?

**Comment by ca-schaefer** [comment]
I updated the README in commit https://github.com/minecraft-saar/spigot-plugin/commit/a8b4d7eae705ecd6c723c7880cdff919a0abd3ff :
In the configuration file `spigot-plugin/communication/src/main/resources/config.yml`, there is the `banPlayers` - `true` if players should be banned after one game, `false` if not.

**Comment by akoehn** [comment]
But that config file is bundled into the jar that is loaded by spigot, right?  In that case, I would not need to recompile the classes but still need to rebundle and repopulate the plugin after a change to the config; or is there a way to only change the config without the other steps?

**Comment by ca-schaefer** [comment]
When the server is started the first time, the config is copied to `spigot-plugin/server/plugins/CommunicationPlugin/config.yml` and can also be changed there. This way, the change is effective as soon as the server is restarted. 

If I remember correctly, the config is only copied if there is no config in `spigot-plugin/server/plugins/CommunicationPlugin/`. So recompiling the Plugin has no effect on the changed config. But if the entire server is set up or the config.yml is deleted otherwise, the changes would be lost because then they are only the the server directory and not in the plugin source files.
